[workspace]
members = ["examples", "logos", "logos-cli", "logos-codegen", "logos-derive", "tests"]
exclude = ["fuzz", "tests/target-cfg"]
resolver = "2"

[workspace.package]
authors = [
    "Maciej Hirsz <hello@maciej.codes>",
    "Jérome Eertmans (maintainer) <jeertmans@icloud.com>",
]
categories = ["parsing", "text-processing"]
description = "Create ridiculously fast Lexers"
edition = "2021"
homepage = "https://logos.maciej.codes/"
keywords = ["lexer", "lexical", "tokenizer", "parser", "no_std"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/maciejhirsz/logos"
rust-version = "1.80.0"
version = "0.16.1"
include = ["build.rs", "/src/", "/benches/", "/tests/", "LICENSE-MIT", "LICENSE-APACHE"]

[profile]
bench = {lto = true}
release = {lto = true}
