# Generated by rust2rpm 26
%bcond_without check

Name:           logos
Version:        0.14.2
Release:        %autorelease
Summary:        Create ridiculously fast Lexers

SourceLicense:  MIT OR Apache-2.0
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/maciejhirsz/logos
Source:         # FIXME

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
Create ridiculously fast Lexers.}

%description %{_description}

%prep
%autosetup -n logos-%{version} -p1

# Remove crates that are not packaged in Fedora
tomcli set Cargo.toml arrays delitem workspace.members logos-cli
tomcli set Cargo.toml arrays delitem workspace.members tests
tomcli set Cargo.toml arrays delitem workspace.members fuzz

%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- --workspace
%endif

%files
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md

%changelog
%autochangelog
