name: no_std

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

defaults:
  run:
    working-directory: tests/target-cfg

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:
  build-nostd:
    name: Build on no_std target (thumbv7em-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv7em-none-eabi
      - uses: taiki-e/install-action@cargo-hack
      # No default features build
      - name: no_std / no feat ${{ matrix.crate }}
        run: cargo build --target thumbv7em-none-eabi --release --no-default-features
      - name: no_std / cargo hack
        run: cargo hack build --target thumbv7em-none-eabi --release --each-feature
