on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Using my fork because there seems to be a bug where it couldn't find `s390x/fedora:latest`
      - uses: LecrisUT/run-on-arch-action@fix/arch-flag
        with:
          distro: none
          arch: s390x
          base_image: "s390x/fedora:latest"
          run: |
            echo "::group::Debug stuff"
            # Double-check we are in the appropriate environment
            uname -a
            echo "::endgroup::"
            
            echo "::group::Install rust environment"
            dnf install -y cargo
            echo "::endgroup::"
            
            echo "::group::Run cargo test"
            # TODO: Help me with this section
            cargo test --workspace --verbose
            echo "::endgroup::"
